# -*- coding: utf-8 -*-
"""2023程式設計01週.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1drVQyXkdZgUh_DByG1DkWd06iBVJJDED

第一週有學 print()
"""

print('Hello World!')

"""input()

"""

a=input()
print(a)

"""現在要學怎麼把數字讀進來"""

a, b = input().split()
print(int(a) + int(b))

"""第一週還有膠結圖:PrintScreen(PrtScn),Alt-PrintScreen,Windows-shift-S三種截圖法
有教Processing畫背景background(255,255)
有教GitHub
"""